export const daftar = [
  {
    id: 1,
    name: "Spagethie",
    price: 12000,
    category: "makanan",
    img: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg",
  },
  {
    id: 2,
    name: "Hamburger",
    price: 15000,
    category: "makanan",
    img: "https://www.foodiesfeed.com/wp-content/uploads/2023/10/bowl-of-ice-cream-with-chocolate.jpg",
  },
  {
    id: 3,
    name: "Es Krim",
    price: 7000,
    category: "cemilan",
    img: "https://www.foodiesfeed.com/wp-content/uploads/2023/08/crispy-spicy-chicken-wings.jpg",
  },
  {
    id: 4,
    name: "Ayam Goreng",
    price: 25000,
    category: "makanan",
    img: "https://www.foodiesfeed.com/wp-content/uploads/2023/06/pouring-honey-on-pancakes.jpg",
  },
  {
    id: 5,
    name: "Serabi",
    price: 5000,
    category: "makanan",
    img: "https://www.foodiesfeed.com/wp-content/uploads/2023/07/fresh-fruit-platter.jpg",
  },
  {
    id: 6,
    name: "Buah Buahan",
    price: 17000,
    category: "cemilan",
    img: "https://www.foodiesfeed.com/wp-content/uploads/2023/08/salted-pretzel.jpg",
  },
  {
    id: 7,
    name: "Roti",
    price: 2000,
    category: "makanan",
    img: "https://www.foodiesfeed.com/wp-content/uploads/2023/04/minestrone-soup.jpg",
  },
  {
    id: 8,
    name: "Zupasup",
    price: 23000,
    category: "cemilan",
    img: "https://www.foodiesfeed.com/wp-content/uploads/2023/06/xiaolongbao-dumplings.jpg",
  },
  {
    id: 9,
    name: "Beer Haram",
    price: 70000,
    category: "minuman",
    img: "https://images.pexels.com/photos/1283219/pexels-photo-1283219.jpeg",
  },
  {
    id: 10,
    name: "Es Jeruk",
    price: 18000,
    category: "makanan",
    img: "https://images.pexels.com/photos/3323682/pexels-photo-3323682.jpeg",
  },
  {
    id: 11,
    name: "Cendol",
    price: 11000,
    category: "minuman",
    img: "https://images.pexels.com/photos/1200348/pexels-photo-1200348.jpeg",
  },
  {
    id: 12,
    name: "Coca Cola",
    price: 8000,
    category: "minuman",
    img: "https://images.pexels.com/photos/1904262/pexels-photo-1904262.jpeg",
  },
];

export const transaksi = [
  {
    id: 1,
    name: "Baim Chao",
    table: 1,
    status: "waiting",
    orders: [
      {
        menus_id: 0,
        quantity: 0,
        price: 0,
        total: 0,
      },
    ],
    sub_total: 0,
    tax: 0,
    total: 1200000,
  },
  {
    id: 2,
    name: "Choyung Fat",
    table: 2,
    status: "waiting",
    orders: [
      {
        menus_id: 0,
        quantity: 0,
        price: 0,
        total: 0,
      },
    ],
    sub_total: 0,
    tax: 0,
    total: 0,
  },
];
